spring:
  application:
    name: patient-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: book_service
#      username:
#      password:
server:
  port: 8080
logging:
  level:
    #    root: WARN
    org:
      mongodb:
        driver: DEBUG
      springframework:
        #        web: WARN
        data:
          core:
            MongoTemplate: DEBUG
            MongoOperations: DEBUG
  pattern:
    console: "%msg%n"