#spring.application.name=DiscoveryService
spring:
  application:
    name: DiscoveryService
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms: 500